dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide Superuser"
  - psql test_decide -c "GRANT ALL ON ALL TABLES IN SCHEMA public to decide;"
  - psql test_decide -c "GRANT ALL ON ALL SEQUENCES IN SCHEMA public to decide;"
  - psql test_decide -c "GRANT ALL ON ALL FUNCTIONS IN SCHEMA public to decide;"
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
script:
  - cd decide
  - coverage run --branch --source=. ./manage.py test census --keepdb
  - coverage xml
  - python-codacy-coverage -r coverage.xml
deploy:
  provider: heroku
  app: proyecto-decide-manpercar1
  strategy: git
  api_key: $HEROKU_AUTH_TOKEN
